//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025Diagram")]

namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// DomainClass CAFAMCMDGProyectoIPS2025Diagram
	/// Description for UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025Diagram
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025Diagram.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025Diagram.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("b65a2db3-8617-4272-b68f-2b5bc43cced4")]
	public partial class CAFAMCMDGProyectoIPS2025Diagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025ToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Diagram styles
		/// <summary>
		/// Initializes style set resources for this shape type
		/// </summary>
		/// <param name="classStyleSet">The style set for this shape class</param>
		protected override void InitializeResources(DslDiagrams::StyleSet classStyleSet)
		{
			base.InitializeResources(classStyleSet);
			
			// Fill brush settings for this shape.
			DslDiagrams::BrushSettings backgroundBrush = new DslDiagrams::BrushSettings();
			backgroundBrush.Color = global::System.Drawing.Color.FromKnownColor(global::System.Drawing.KnownColor.Gold);
			classStyleSet.OverrideBrush(DslDiagrams::DiagramBrushes.DiagramBackground, backgroundBrush);
		
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacion)
			{
				global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacionShape newShape = new global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacionShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion)
			{
				global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionShape newShape = new global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad)
			{
				global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadShape newShape = new global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
		}
		
		#endregion
		#region Constructors, domain class Id
	
		/// <summary>
		/// CAFAMCMDGProyectoIPS2025Diagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xb65a2db3, 0x8617, 0x4272, 0xb6, 0x8f, 0x2b, 0x5b, 0xc4, 0x3c, 0xce, 0xd4);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public CAFAMCMDGProyectoIPS2025Diagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public CAFAMCMDGProyectoIPS2025Diagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacion)
				{
					parentElement = GetParentForAtributoRelacion((global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacion)childElement);
				} else
				if(childElement is global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion)
				{
					parentElement = GetParentForRelacion((global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion)childElement);
				} else
				if(childElement is global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad)
				{
					parentElement = GetParentForEntidad((global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBD GetParentForRelacion( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion root )
			{
				// Segments 0 and 1
				global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBD result = root.DenWebBD;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBD GetParentForAtributoRelacion( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacion root )
			{
				// Segments 0 and 1
				global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion root2 = root.Relacion;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBD result = root2.DenWebBD;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBD GetParentForEntidad( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad root )
			{
				// Segments 0 and 1
				global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion root2 = root.Relacion;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBD result = root2.DenWebBD;
				if ( result == null ) return null;
				return result;
			}
		}
		
	
	}
