//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// DomainModel CAFAMCMDGProyectoIPS2025DomainModel
	/// Description for UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("e291b965-1ceb-485c-a1b8-86cdd868b96c")]
	public partial class CAFAMCMDGProyectoIPS2025DomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// CAFAMCMDGProyectoIPS2025DomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0xe291b965, 0x1ceb, 0x485c, 0xa1, 0xb8, 0x86, 0xcd, 0xd8, 0x68, 0xb9, 0x6c);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public CAFAMCMDGProyectoIPS2025DomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(DenWebBD),
				typeof(Entidad),
				typeof(Relacion),
				typeof(Atributo),
				typeof(AtributoEntidad),
				typeof(AtributoRelacion),
				typeof(AtributoClave),
				typeof(DenWebBDTieneRelacion),
				typeof(EntidadTieneAtributoClave),
				typeof(RelacionTieneAtributoRelacion),
				typeof(EntidadTieneAtributoEntidad),
				typeof(RelacionTieneEntidad),
				typeof(CAFAMCMDGProyectoIPS2025Diagram),
				typeof(EntidadShape),
				typeof(RelacionShape),
				typeof(AtributoClaveShape),
				typeof(AtributoEntidadShape),
				typeof(AtributoRelacionShape),
				typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.FixUpDiagram),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Entidad), "nombre", Entidad.nombreDomainPropertyId, typeof(Entidad.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Relacion), "nombre", Relacion.nombreDomainPropertyId, typeof(Relacion.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Relacion), "cMax", Relacion.cMaxDomainPropertyId, typeof(Relacion.cMaxPropertyHandler)),
				new DomainMemberInfo(typeof(Relacion), "cMin", Relacion.cMinDomainPropertyId, typeof(Relacion.cMinPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "nombre", Atributo.nombreDomainPropertyId, typeof(Atributo.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "tipo", Atributo.tipoDomainPropertyId, typeof(Atributo.tipoPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoClave), "DomainProperty1", AtributoClave.DomainProperty1DomainPropertyId, typeof(AtributoClave.DomainProperty1PropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(DenWebBDTieneRelacion), "DenWebBD", DenWebBDTieneRelacion.DenWebBDDomainRoleId),
				new DomainRolePlayerInfo(typeof(DenWebBDTieneRelacion), "Relacion", DenWebBDTieneRelacion.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadTieneAtributoClave), "Entidad", EntidadTieneAtributoClave.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadTieneAtributoClave), "AtributoClave", EntidadTieneAtributoClave.AtributoClaveDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionTieneAtributoRelacion), "Relacion", RelacionTieneAtributoRelacion.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionTieneAtributoRelacion), "AtributoRelacion", RelacionTieneAtributoRelacion.AtributoRelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadTieneAtributoEntidad), "Entidad", EntidadTieneAtributoEntidad.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadTieneAtributoEntidad), "AtributoEntidad", EntidadTieneAtributoEntidad.AtributoEntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionTieneEntidad), "Relacion", RelacionTieneEntidad.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(RelacionTieneEntidad), "Entidad", RelacionTieneEntidad.EntidadDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(13);
				createElementMap.Add(typeof(DenWebBD), 0);
				createElementMap.Add(typeof(Entidad), 1);
				createElementMap.Add(typeof(Relacion), 2);
				createElementMap.Add(typeof(AtributoEntidad), 3);
				createElementMap.Add(typeof(AtributoRelacion), 4);
				createElementMap.Add(typeof(AtributoClave), 5);
				createElementMap.Add(typeof(CAFAMCMDGProyectoIPS2025Diagram), 6);
				createElementMap.Add(typeof(EntidadShape), 7);
				createElementMap.Add(typeof(RelacionShape), 8);
				createElementMap.Add(typeof(AtributoClaveShape), 9);
				createElementMap.Add(typeof(AtributoEntidadShape), 10);
				createElementMap.Add(typeof(AtributoRelacionShape), 11);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new DenWebBD(partition, propertyAssignments);
				case 1: return new Entidad(partition, propertyAssignments);
				case 2: return new Relacion(partition, propertyAssignments);
				case 3: return new AtributoEntidad(partition, propertyAssignments);
				case 4: return new AtributoRelacion(partition, propertyAssignments);
				case 5: return new AtributoClave(partition, propertyAssignments);
				case 6: return new CAFAMCMDGProyectoIPS2025Diagram(partition, propertyAssignments);
				case 7: return new EntidadShape(partition, propertyAssignments);
				case 8: return new RelacionShape(partition, propertyAssignments);
				case 9: return new AtributoClaveShape(partition, propertyAssignments);
				case 10: return new AtributoEntidadShape(partition, propertyAssignments);
				case 11: return new AtributoRelacionShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(5);
				createElementLinkMap.Add(typeof(DenWebBDTieneRelacion), 0);
				createElementLinkMap.Add(typeof(EntidadTieneAtributoClave), 1);
				createElementLinkMap.Add(typeof(RelacionTieneAtributoRelacion), 2);
				createElementLinkMap.Add(typeof(EntidadTieneAtributoEntidad), 3);
				createElementLinkMap.Add(typeof(RelacionTieneEntidad), 4);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new DenWebBDTieneRelacion(partition, roleAssignments, propertyAssignments);
				case 1: return new EntidadTieneAtributoClave(partition, roleAssignments, propertyAssignments);
				case 2: return new RelacionTieneAtributoRelacion(partition, roleAssignments, propertyAssignments);
				case 3: return new EntidadTieneAtributoEntidad(partition, roleAssignments, propertyAssignments);
				case 4: return new RelacionTieneEntidad(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return CAFAMCMDGProyectoIPS2025DomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (CAFAMCMDGProyectoIPS2025DomainModel.resourceManager == null)
				{
					CAFAMCMDGProyectoIPS2025DomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(CAFAMCMDGProyectoIPS2025DomainModel).Assembly);
				}
				return CAFAMCMDGProyectoIPS2025DomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return CAFAMCMDGProyectoIPS2025DomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return CAFAMCMDGProyectoIPS2025DomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (CAFAMCMDGProyectoIPS2025DomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new CAFAMCMDGProyectoIPS2025CopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					CAFAMCMDGProyectoIPS2025DomainModel.copyClosure = copyFilter;
				}
				return CAFAMCMDGProyectoIPS2025DomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (CAFAMCMDGProyectoIPS2025DomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new CAFAMCMDGProyectoIPS2025DeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					CAFAMCMDGProyectoIPS2025DomainModel.removeClosure = removeFilter;
				}
				return CAFAMCMDGProyectoIPS2025DomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.FixUpDiagram));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.FixUpDiagram));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class CAFAMCMDGProyectoIPS2025DeleteClosure : CAFAMCMDGProyectoIPS2025DeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public CAFAMCMDGProyectoIPS2025DeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class CAFAMCMDGProyectoIPS2025DeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public CAFAMCMDGProyectoIPS2025DeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.RelacionDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.AtributoClaveDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.AtributoRelacionDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.AtributoEntidadDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneEntidad.EntidadDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class CAFAMCMDGProyectoIPS2025CopyClosure : CAFAMCMDGProyectoIPS2025CopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public CAFAMCMDGProyectoIPS2025CopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class CAFAMCMDGProyectoIPS2025CopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public CAFAMCMDGProyectoIPS2025CopyClosureBase():base()
		{
		}
	}
	#endregion
		
}

