//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// DomainRelationship DenWebBDTieneRelacion
	/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("ac4393a0-c085-4d63-81f8-f069de952381")]
	public partial class DenWebBDTieneRelacion : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// DenWebBDTieneRelacion domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xac4393a0, 0xc085, 0x4d63, 0x81, 0xf8, 0xf0, 0x69, 0xde, 0x95, 0x23, 0x81);
	
				
		/// <summary>
		/// Constructor
		/// Creates a DenWebBDTieneRelacion link in the same Partition as the given DenWebBD
		/// </summary>
		/// <param name="source">DenWebBD to use as the source of the relationship.</param>
		/// <param name="target">Relacion to use as the target of the relationship.</param>
		public DenWebBDTieneRelacion(DenWebBD source, Relacion target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(DenWebBDTieneRelacion.DenWebBDDomainRoleId, source), new DslModeling::RoleAssignment(DenWebBDTieneRelacion.RelacionDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public DenWebBDTieneRelacion(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public DenWebBDTieneRelacion(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public DenWebBDTieneRelacion(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public DenWebBDTieneRelacion(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region DenWebBD domain role code
		
		/// <summary>
		/// DenWebBD domain role Id.
		/// </summary>
		public static readonly global::System.Guid DenWebBDDomainRoleId = new global::System.Guid(0xcd0b19cf, 0x92d4, 0x4455, 0xb9, 0x30, 0x4c, 0xa7, 0x2e, 0x00, 0x07, 0xf6);
		
		/// <summary>
		/// DomainRole DenWebBD
		/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.DenWebBD
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion/DenWebBD.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion/DenWebBD.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Relacion", PropertyDisplayNameKey="UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion/DenWebBD.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("cd0b19cf-92d4-4455-b930-4ca72e0007f6")]
		public virtual DenWebBD DenWebBD
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (DenWebBD)DslModeling::DomainRoleInfo.GetRolePlayer(this, DenWebBDDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, DenWebBDDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access DenWebBD of a Relacion
		/// <summary>
		/// Gets DenWebBD.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DenWebBD GetDenWebBD(Relacion element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, RelacionDomainRoleId) as DenWebBD;
		}
		
		/// <summary>
		/// Sets DenWebBD.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetDenWebBD(Relacion element, DenWebBD newDenWebBD)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, RelacionDomainRoleId, newDenWebBD);
		}
		#endregion
		#region Relacion domain role code
		
		/// <summary>
		/// Relacion domain role Id.
		/// </summary>
		public static readonly global::System.Guid RelacionDomainRoleId = new global::System.Guid(0x777cc166, 0xf6f2, 0x4ce3, 0xb2, 0xef, 0x15, 0x68, 0x49, 0x66, 0xf3, 0x00);
		
		/// <summary>
		/// DomainRole Relacion
		/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.Relacion
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion/Relacion.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion/Relacion.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "DenWebBD", PropertyDisplayNameKey="UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion/Relacion.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("777cc166-f6f2-4ce3-b2ef-15684966f300")]
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Relacion)DslModeling::DomainRoleInfo.GetRolePlayer(this, RelacionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, RelacionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Relacion of a DenWebBD
		/// <summary>
		/// Gets a list of Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Relacion> GetRelacion(DenWebBD element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(element, DenWebBDDomainRoleId);
		}
		#endregion
		#region DenWebBD link accessor
		/// <summary>
		/// Get the list of DenWebBDTieneRelacion links to a DenWebBD.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion> GetLinksToRelacion ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBD denWebBDInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion>(denWebBDInstance, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.DenWebBDDomainRoleId);
		}
		#endregion
		#region Relacion link accessor
		/// <summary>
		/// Get the DenWebBDTieneRelacion link to a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion GetLinkToDenWebBD (global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion relacionInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion>(relacionInstance, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.RelacionDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Relacion not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region DenWebBDTieneRelacion instance accessors
		
		/// <summary>
		/// Get any DenWebBDTieneRelacion links between a given DenWebBD and a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion> GetLinks( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBD source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion>();
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion>(source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.DenWebBDDomainRoleId);
			foreach ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one DenWebBDTieneRelacion link between a given DenWebBDand a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion GetLink( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBD source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion>(source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.DenWebBDDomainRoleId);
			foreach ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// DomainRelationship EntidadTieneAtributoClave
	/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("bb479729-9342-4977-9d7b-933ee9d3154d")]
	public partial class EntidadTieneAtributoClave : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadTieneAtributoClave domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xbb479729, 0x9342, 0x4977, 0x9d, 0x7b, 0x93, 0x3e, 0xe9, 0xd3, 0x15, 0x4d);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadTieneAtributoClave link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">AtributoClave to use as the target of the relationship.</param>
		public EntidadTieneAtributoClave(Entidad source, AtributoClave target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadTieneAtributoClave.EntidadDomainRoleId, source), new DslModeling::RoleAssignment(EntidadTieneAtributoClave.AtributoClaveDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadTieneAtributoClave(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadTieneAtributoClave(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadTieneAtributoClave(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadTieneAtributoClave(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0x30e9e6bb, 0x992d, 0x4b66, 0x96, 0x15, 0xe4, 0xe0, 0xc7, 0xdf, 0x52, 0x5a);
		
		/// <summary>
		/// DomainRole Entidad
		/// Descripción de
		/// UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave/Entidad.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave/Entidad.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "AtributoClave", PropertyDisplayNameKey="UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave/Entidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("30e9e6bb-992d-4b66-9615-e4e0c7df525a")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a AtributoClave
		/// <summary>
		/// Gets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Entidad GetEntidad(AtributoClave element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, AtributoClaveDomainRoleId) as Entidad;
		}
		
		/// <summary>
		/// Sets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetEntidad(AtributoClave element, Entidad newEntidad)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, AtributoClaveDomainRoleId, newEntidad);
		}
		#endregion
		#region AtributoClave domain role code
		
		/// <summary>
		/// AtributoClave domain role Id.
		/// </summary>
		public static readonly global::System.Guid AtributoClaveDomainRoleId = new global::System.Guid(0x63256289, 0x4f01, 0x4824, 0xaa, 0x4a, 0xfa, 0x53, 0x5a, 0x80, 0x42, 0x09);
		
		/// <summary>
		/// DomainRole AtributoClave
		/// Descripción de
		/// UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.AtributoClave
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave/AtributoClave.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave/AtributoClave.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave/AtributoClave.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("63256289-4f01-4824-aa4a-fa535a804209")]
		public virtual AtributoClave AtributoClave
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (AtributoClave)DslModeling::DomainRoleInfo.GetRolePlayer(this, AtributoClaveDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, AtributoClaveDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access AtributoClave of a Entidad
		/// <summary>
		/// Gets a list of AtributoClave.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<AtributoClave> GetAtributoClave(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoClave>, AtributoClave>(element, EntidadDomainRoleId);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the list of EntidadTieneAtributoClave links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave> GetLinksToAtributoClave ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad entidadInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave>(entidadInstance, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.EntidadDomainRoleId);
		}
		#endregion
		#region AtributoClave link accessor
		/// <summary>
		/// Get the EntidadTieneAtributoClave link to a AtributoClave.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave GetLinkToEntidad (global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoClave atributoClaveInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave>(atributoClaveInstance, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.AtributoClaveDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of AtributoClave not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region EntidadTieneAtributoClave instance accessors
		
		/// <summary>
		/// Get any EntidadTieneAtributoClave links between a given Entidad and a AtributoClave.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave> GetLinks( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoClave target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave>();
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave>(source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave link in links )
			{
				if ( target.Equals(link.AtributoClave) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadTieneAtributoClave link between a given Entidadand a AtributoClave.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave GetLink( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoClave target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave>(source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave link in links )
			{
				if ( target.Equals(link.AtributoClave) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// DomainRelationship RelacionTieneAtributoRelacion
	/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("fa39ea83-3457-45d8-ac97-caf5340e307f")]
	public partial class RelacionTieneAtributoRelacion : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// RelacionTieneAtributoRelacion domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xfa39ea83, 0x3457, 0x45d8, 0xac, 0x97, 0xca, 0xf5, 0x34, 0x0e, 0x30, 0x7f);
	
				
		/// <summary>
		/// Constructor
		/// Creates a RelacionTieneAtributoRelacion link in the same Partition as the given Relacion
		/// </summary>
		/// <param name="source">Relacion to use as the source of the relationship.</param>
		/// <param name="target">AtributoRelacion to use as the target of the relationship.</param>
		public RelacionTieneAtributoRelacion(Relacion source, AtributoRelacion target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(RelacionTieneAtributoRelacion.RelacionDomainRoleId, source), new DslModeling::RoleAssignment(RelacionTieneAtributoRelacion.AtributoRelacionDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public RelacionTieneAtributoRelacion(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public RelacionTieneAtributoRelacion(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public RelacionTieneAtributoRelacion(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public RelacionTieneAtributoRelacion(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Relacion domain role code
		
		/// <summary>
		/// Relacion domain role Id.
		/// </summary>
		public static readonly global::System.Guid RelacionDomainRoleId = new global::System.Guid(0x7d31feaf, 0x2d03, 0x49f0, 0xa0, 0x19, 0xfb, 0x9c, 0x19, 0x1f, 0x2b, 0xe0);
		
		/// <summary>
		/// DomainRole Relacion
		/// Descripción de
		/// UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.Relacion
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion/Relacion.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion/Relacion.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "AtributoRelacion", PropertyDisplayNameKey="UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion/Relacion.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("7d31feaf-2d03-49f0-a019-fb9c191f2be0")]
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Relacion)DslModeling::DomainRoleInfo.GetRolePlayer(this, RelacionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, RelacionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Relacion of a AtributoRelacion
		/// <summary>
		/// Gets Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Relacion GetRelacion(AtributoRelacion element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, AtributoRelacionDomainRoleId) as Relacion;
		}
		
		/// <summary>
		/// Sets Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetRelacion(AtributoRelacion element, Relacion newRelacion)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, AtributoRelacionDomainRoleId, newRelacion);
		}
		#endregion
		#region AtributoRelacion domain role code
		
		/// <summary>
		/// AtributoRelacion domain role Id.
		/// </summary>
		public static readonly global::System.Guid AtributoRelacionDomainRoleId = new global::System.Guid(0xf3c39e0d, 0x7dbf, 0x4996, 0x9f, 0x88, 0xb1, 0x8a, 0x2c, 0x8b, 0x8e, 0xae);
		
		/// <summary>
		/// DomainRole AtributoRelacion
		/// Descripción de
		/// UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.AtributoRelacion
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion/AtributoRelacion.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion/AtributoRelacion.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Relacion", PropertyDisplayNameKey="UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion/AtributoRelacion.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("f3c39e0d-7dbf-4996-9f88-b18a2c8b8eae")]
		public virtual AtributoRelacion AtributoRelacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (AtributoRelacion)DslModeling::DomainRoleInfo.GetRolePlayer(this, AtributoRelacionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, AtributoRelacionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access AtributoRelacion of a Relacion
		/// <summary>
		/// Gets a list of AtributoRelacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<AtributoRelacion> GetAtributoRelacion(Relacion element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoRelacion>, AtributoRelacion>(element, RelacionDomainRoleId);
		}
		#endregion
		#region Relacion link accessor
		/// <summary>
		/// Get the list of RelacionTieneAtributoRelacion links to a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion> GetLinksToAtributoRelacion ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion relacionInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion>(relacionInstance, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.RelacionDomainRoleId);
		}
		#endregion
		#region AtributoRelacion link accessor
		/// <summary>
		/// Get the RelacionTieneAtributoRelacion link to a AtributoRelacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion GetLinkToRelacion (global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacion atributoRelacionInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion>(atributoRelacionInstance, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.AtributoRelacionDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of AtributoRelacion not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region RelacionTieneAtributoRelacion instance accessors
		
		/// <summary>
		/// Get any RelacionTieneAtributoRelacion links between a given Relacion and a AtributoRelacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion> GetLinks( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacion target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion>();
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion>(source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.RelacionDomainRoleId);
			foreach ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion link in links )
			{
				if ( target.Equals(link.AtributoRelacion) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one RelacionTieneAtributoRelacion link between a given Relacionand a AtributoRelacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion GetLink( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacion target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion>(source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.RelacionDomainRoleId);
			foreach ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion link in links )
			{
				if ( target.Equals(link.AtributoRelacion) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// DomainRelationship EntidadTieneAtributoEntidad
	/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("f46fd933-4e0f-4b4f-8e68-6054bceaf4b2")]
	public partial class EntidadTieneAtributoEntidad : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadTieneAtributoEntidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xf46fd933, 0x4e0f, 0x4b4f, 0x8e, 0x68, 0x60, 0x54, 0xbc, 0xea, 0xf4, 0xb2);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadTieneAtributoEntidad link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">AtributoEntidad to use as the target of the relationship.</param>
		public EntidadTieneAtributoEntidad(Entidad source, AtributoEntidad target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadTieneAtributoEntidad.EntidadDomainRoleId, source), new DslModeling::RoleAssignment(EntidadTieneAtributoEntidad.AtributoEntidadDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadTieneAtributoEntidad(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadTieneAtributoEntidad(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadTieneAtributoEntidad(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadTieneAtributoEntidad(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0x6dc298b2, 0x62e8, 0x422f, 0x8e, 0x36, 0xfe, 0x1f, 0x47, 0xea, 0x23, 0xd6);
		
		/// <summary>
		/// DomainRole Entidad
		/// Descripción de
		/// UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad/Entidad.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad/Entidad.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "AtributoEntidad", PropertyDisplayNameKey="UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad/Entidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("6dc298b2-62e8-422f-8e36-fe1f47ea23d6")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a AtributoEntidad
		/// <summary>
		/// Gets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Entidad GetEntidad(AtributoEntidad element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, AtributoEntidadDomainRoleId) as Entidad;
		}
		
		/// <summary>
		/// Sets Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetEntidad(AtributoEntidad element, Entidad newEntidad)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, AtributoEntidadDomainRoleId, newEntidad);
		}
		#endregion
		#region AtributoEntidad domain role code
		
		/// <summary>
		/// AtributoEntidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid AtributoEntidadDomainRoleId = new global::System.Guid(0x10203564, 0x5cfa, 0x4c5c, 0xa1, 0x28, 0x2c, 0x71, 0x38, 0x24, 0xa7, 0xa0);
		
		/// <summary>
		/// DomainRole AtributoEntidad
		/// Descripción de
		/// UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.AtributoEntidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad/AtributoEntidad.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad/AtributoEntidad.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad/AtributoEntidad.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroOne)]
		[DslModeling::DomainObjectId("10203564-5cfa-4c5c-a128-2c713824a7a0")]
		public virtual AtributoEntidad AtributoEntidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (AtributoEntidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, AtributoEntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, AtributoEntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access AtributoEntidad of a Entidad
		/// <summary>
		/// Gets a list of AtributoEntidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<AtributoEntidad> GetAtributoEntidad(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoEntidad>, AtributoEntidad>(element, EntidadDomainRoleId);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the list of EntidadTieneAtributoEntidad links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad> GetLinksToAtributoEntidad ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad entidadInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad>(entidadInstance, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.EntidadDomainRoleId);
		}
		#endregion
		#region AtributoEntidad link accessor
		/// <summary>
		/// Get the EntidadTieneAtributoEntidad link to a AtributoEntidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad GetLinkToEntidad (global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoEntidad atributoEntidadInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad>(atributoEntidadInstance, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.AtributoEntidadDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of AtributoEntidad not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region EntidadTieneAtributoEntidad instance accessors
		
		/// <summary>
		/// Get any EntidadTieneAtributoEntidad links between a given Entidad and a AtributoEntidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad> GetLinks( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoEntidad target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad>();
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad>(source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad link in links )
			{
				if ( target.Equals(link.AtributoEntidad) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadTieneAtributoEntidad link between a given Entidadand a AtributoEntidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad GetLink( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoEntidad target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad>(source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad link in links )
			{
				if ( target.Equals(link.AtributoEntidad) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// DomainRelationship EntidadReferenciasRelacion
	/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship()]
	[DslModeling::DomainObjectId("35f74ecf-6a5a-4bdc-a11b-b4ff58c5ed5a")]
	public partial class EntidadReferenciasRelacion : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EntidadReferenciasRelacion domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x35f74ecf, 0x6a5a, 0x4bdc, 0xa1, 0x1b, 0xb4, 0xff, 0x58, 0xc5, 0xed, 0x5a);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EntidadReferenciasRelacion link in the same Partition as the given Entidad
		/// </summary>
		/// <param name="source">Entidad to use as the source of the relationship.</param>
		/// <param name="target">Relacion to use as the target of the relationship.</param>
		public EntidadReferenciasRelacion(Entidad source, Relacion target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EntidadReferenciasRelacion.EntidadDomainRoleId, source), new DslModeling::RoleAssignment(EntidadReferenciasRelacion.RelacionDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadReferenciasRelacion(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadReferenciasRelacion(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EntidadReferenciasRelacion(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EntidadReferenciasRelacion(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0x0cb394bf, 0x701b, 0x4d65, 0xab, 0xad, 0x9b, 0x09, 0xfc, 0xa9, 0x94, 0xd0);
		
		/// <summary>
		/// DomainRole Entidad
		/// Descripción de
		/// UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion/Entidad.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion/Entidad.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Relacion", PropertyDisplayNameKey="UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion/Entidad.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("0cb394bf-701b-4d65-abad-9b09fca994d0")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a Relacion
		/// <summary>
		/// Gets a list of Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Entidad> GetEntidad(Relacion element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(element, RelacionDomainRoleId);
		}
		#endregion
		#region Relacion domain role code
		
		/// <summary>
		/// Relacion domain role Id.
		/// </summary>
		public static readonly global::System.Guid RelacionDomainRoleId = new global::System.Guid(0xaa707804, 0xaa60, 0x4d99, 0xa5, 0xc4, 0xb3, 0x31, 0x1c, 0x88, 0x44, 0x65);
		
		/// <summary>
		/// DomainRole Relacion
		/// Descripción de
		/// UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion.Relacion
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion/Relacion.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion/Relacion.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion/Relacion.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("aa707804-aa60-4d99-a5c4-b3311c884465")]
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Relacion)DslModeling::DomainRoleInfo.GetRolePlayer(this, RelacionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, RelacionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Relacion of a Entidad
		/// <summary>
		/// Gets a list of Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Relacion> GetRelacion(Entidad element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(element, EntidadDomainRoleId);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the list of EntidadReferenciasRelacion links to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion> GetLinksToRelacion ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad entidadInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion>(entidadInstance, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion.EntidadDomainRoleId);
		}
		#endregion
		#region Relacion link accessor
		/// <summary>
		/// Get the list of EntidadReferenciasRelacion links to a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion> GetLinksToEntidad ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion relacionInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion>(relacionInstance, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion.RelacionDomainRoleId);
		}
		#endregion
		#region EntidadReferenciasRelacion instance accessors
		
		/// <summary>
		/// Get any EntidadReferenciasRelacion links between a given Entidad and a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion> GetLinks( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion>();
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion>(source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EntidadReferenciasRelacion link between a given Entidadand a Relacion.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion GetLink( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion>(source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion.EntidadDomainRoleId);
			foreach ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion link in links )
			{
				if ( target.Equals(link.Relacion) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// DomainRelationship DenWebBDTieneEntidad
	/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("f5667def-dafe-4290-a9ec-9cef6c228bdd")]
	public partial class DenWebBDTieneEntidad : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// DenWebBDTieneEntidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xf5667def, 0xdafe, 0x4290, 0xa9, 0xec, 0x9c, 0xef, 0x6c, 0x22, 0x8b, 0xdd);
	
				
		/// <summary>
		/// Constructor
		/// Creates a DenWebBDTieneEntidad link in the same Partition as the given DenWebBD
		/// </summary>
		/// <param name="source">DenWebBD to use as the source of the relationship.</param>
		/// <param name="target">Entidad to use as the target of the relationship.</param>
		public DenWebBDTieneEntidad(DenWebBD source, Entidad target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(DenWebBDTieneEntidad.DenWebBDDomainRoleId, source), new DslModeling::RoleAssignment(DenWebBDTieneEntidad.EntidadDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public DenWebBDTieneEntidad(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public DenWebBDTieneEntidad(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public DenWebBDTieneEntidad(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public DenWebBDTieneEntidad(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region DenWebBD domain role code
		
		/// <summary>
		/// DenWebBD domain role Id.
		/// </summary>
		public static readonly global::System.Guid DenWebBDDomainRoleId = new global::System.Guid(0xb050ccbd, 0xc286, 0x4614, 0x98, 0x51, 0x68, 0x45, 0xcb, 0xfc, 0x9f, 0x5c);
		
		/// <summary>
		/// DomainRole DenWebBD
		/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad.DenWebBD
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad/DenWebBD.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad/DenWebBD.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Entidad", PropertyDisplayNameKey="UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad/DenWebBD.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("b050ccbd-c286-4614-9851-6845cbfc9f5c")]
		public virtual DenWebBD DenWebBD
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (DenWebBD)DslModeling::DomainRoleInfo.GetRolePlayer(this, DenWebBDDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, DenWebBDDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access DenWebBD of a Entidad
		/// <summary>
		/// Gets DenWebBD.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DenWebBD GetDenWebBD(Entidad element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, EntidadDomainRoleId) as DenWebBD;
		}
		
		/// <summary>
		/// Sets DenWebBD.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetDenWebBD(Entidad element, DenWebBD newDenWebBD)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, EntidadDomainRoleId, newDenWebBD);
		}
		#endregion
		#region Entidad domain role code
		
		/// <summary>
		/// Entidad domain role Id.
		/// </summary>
		public static readonly global::System.Guid EntidadDomainRoleId = new global::System.Guid(0x54477751, 0x9f11, 0x4e2e, 0x9f, 0x73, 0x14, 0x4f, 0xe4, 0x63, 0xdf, 0x6d);
		
		/// <summary>
		/// DomainRole Entidad
		/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad.Entidad
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad/Entidad.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad/Entidad.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "DenWebBD", PropertyDisplayNameKey="UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad/Entidad.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("54477751-9f11-4e2e-9f73-144fe463df6d")]
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Entidad)DslModeling::DomainRoleInfo.GetRolePlayer(this, EntidadDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EntidadDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Entidad of a DenWebBD
		/// <summary>
		/// Gets a list of Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Entidad> GetEntidad(DenWebBD element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(element, DenWebBDDomainRoleId);
		}
		#endregion
		#region DenWebBD link accessor
		/// <summary>
		/// Get the list of DenWebBDTieneEntidad links to a DenWebBD.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad> GetLinksToEntidad ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBD denWebBDInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad>(denWebBDInstance, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad.DenWebBDDomainRoleId);
		}
		#endregion
		#region Entidad link accessor
		/// <summary>
		/// Get the DenWebBDTieneEntidad link to a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad GetLinkToDenWebBD (global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad entidadInstance)
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad>(entidadInstance, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad.EntidadDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Entidad not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region DenWebBDTieneEntidad instance accessors
		
		/// <summary>
		/// Get any DenWebBDTieneEntidad links between a given DenWebBD and a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad> GetLinks( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBD source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad target )
		{
			global::System.Collections.Generic.List<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad> outLinks = new global::System.Collections.Generic.List<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad>();
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad>(source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad.DenWebBDDomainRoleId);
			foreach ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad link in links )
			{
				if ( target.Equals(link.Entidad) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one DenWebBDTieneEntidad link between a given DenWebBDand a Entidad.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad GetLink( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBD source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad target )
		{
			global::System.Collections.Generic.IList<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad> links = DslModeling::DomainRoleInfo.GetElementLinks<global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad>(source, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad.DenWebBDDomainRoleId);
			foreach ( global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad link in links )
			{
				if ( target.Equals(link.Entidad) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
