//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// DomainClass DenWebBD
	/// The root in which all other elements are embedded. Appears as a diagram.
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBD.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBD.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("038a43b9-c2a3-4e13-91a0-221bf1752350")]
	public partial class DenWebBD : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// DenWebBD domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x038a43b9, 0xc2a3, 0x4e13, 0x91, 0xa0, 0x22, 0x1b, 0xf1, 0x75, 0x23, 0x50);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public DenWebBD(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public DenWebBD(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Relacion opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Relacion.
		/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.DenWebBD
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Relacion> Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.DenWebBDDomainRoleId);
			}
		}
		#endregion
		#region Entidad opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Entidad.
		/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad.DenWebBD
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Entidad> Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad.DenWebBDDomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion.DomainClassId)) 
				{
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion sourceRelacion1 = sourceElement as global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion;
			if (sourceRelacion1 != null)
			{
				// Create link for path DenWebBDTieneRelacion.Relacion
				this.Relacion.Add(sourceRelacion1);

				return;
			}
				
			global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad sourceEntidad2 = sourceElement as global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad;
			if (sourceEntidad2 != null)
			{
				// Create link for path DenWebBDTieneEntidad.Entidad
				this.Entidad.Add(sourceEntidad2);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion sourceRelacion1 = sourceElement as global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion;
			if (sourceRelacion1 != null)
			{
				// Delete link for path DenWebBDTieneRelacion.Relacion
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.GetLinks((global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBD)this, sourceRelacion1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.DenWebBDDomainRoleId, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.RelacionDomainRoleId);
				}

				return;
			}
				
			global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad sourceEntidad2 = sourceElement as global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad;
			if (sourceEntidad2 != null)
			{
				// Delete link for path DenWebBDTieneEntidad.Entidad
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad.GetLinks((global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBD)this, sourceEntidad2))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad.DenWebBDDomainRoleId, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad.EntidadDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// DomainClass Entidad
	/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("6ca7433c-00f7-436a-8135-ce577eda80c8")]
	public partial class Entidad : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Entidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x6ca7433c, 0x00f7, 0x436a, 0x81, 0x35, 0xce, 0x57, 0x7e, 0xda, 0x80, 0xc8);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Entidad(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Entidad(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region nombre domain property code
		
		/// <summary>
		/// nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid nombreDomainPropertyId = new global::System.Guid(0xeedaa762, 0x20a6, 0x47e5, 0x92, 0xde, 0x38, 0x30, 0xa4, 0xe6, 0x48, 0x87);
		
		/// <summary>
		/// Storage for nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of nombre domain property.
		/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad.Nombre
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad/nombre.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad/nombre.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("eedaa762-20a6-47e5-92de-3830a4e64887")]
		public global::System.String nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				nombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Entidad.nombre domain property.
		/// </summary>
		internal sealed partial class nombrePropertyHandler : DslModeling::DomainPropertyValueHandler<Entidad, global::System.String>
		{
			private nombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Entidad.nombre domain property value handler.
			/// </summary>
			public static readonly nombrePropertyHandler Instance = new nombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Entidad.nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return nombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Entidad element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Entidad element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region AtributoClave opposite domain role accessor
		
		/// <summary>
		/// Gets a list of AtributoClave.
		/// Descripción de
		/// UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.Entidad
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<AtributoClave> AtributoClave
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoClave>, AtributoClave>(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.EntidadDomainRoleId);
			}
		}
		#endregion
		#region AtributoEntidad opposite domain role accessor
		
		/// <summary>
		/// Gets a list of AtributoEntidad.
		/// Descripción de
		/// UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.Entidad
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<AtributoEntidad> AtributoEntidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoEntidad>, AtributoEntidad>(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.EntidadDomainRoleId);
			}
		}
		#endregion
		#region Relacion opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Relacion.
		/// Descripción de
		/// UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion.Entidad
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Relacion> Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Relacion>, Relacion>(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion.EntidadDomainRoleId);
			}
		}
		#endregion
		#region DenWebBD opposite domain role accessor
		/// <summary>
		/// Gets or sets DenWebBD.
		/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad.Entidad
		/// </summary>
		public virtual DenWebBD DenWebBD
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad.EntidadDomainRoleId) as DenWebBD;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneEntidad.EntidadDomainRoleId, value);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoClave.DomainClassId)) 
				{
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoEntidad.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoClave sourceAtributoClave1 = sourceElement as global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoClave;
			if (sourceAtributoClave1 != null)
			{
				// Create link for path EntidadTieneAtributoClave.AtributoClave
				this.AtributoClave.Add(sourceAtributoClave1);

				return;
			}
				
			global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoEntidad sourceAtributoEntidad2 = sourceElement as global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoEntidad;
			if (sourceAtributoEntidad2 != null)
			{
				// Create link for path EntidadTieneAtributoEntidad.AtributoEntidad
				this.AtributoEntidad.Add(sourceAtributoEntidad2);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoClave sourceAtributoClave1 = sourceElement as global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoClave;
			if (sourceAtributoClave1 != null)
			{
				// Delete link for path EntidadTieneAtributoClave.AtributoClave
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.GetLinks((global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad)this, sourceAtributoClave1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.EntidadDomainRoleId, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.AtributoClaveDomainRoleId);
				}

				return;
			}
				
			global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoEntidad sourceAtributoEntidad2 = sourceElement as global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoEntidad;
			if (sourceAtributoEntidad2 != null)
			{
				// Delete link for path EntidadTieneAtributoEntidad.AtributoEntidad
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.GetLinks((global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Entidad)this, sourceAtributoEntidad2))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.EntidadDomainRoleId, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.AtributoEntidadDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// DomainClass Relacion
	/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("cbe2fce4-061f-40bb-a584-83b250f6dfa5")]
	public partial class Relacion : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Relacion domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xcbe2fce4, 0x061f, 0x40bb, 0xa5, 0x84, 0x83, 0xb2, 0x50, 0xf6, 0xdf, 0xa5);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Relacion(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Relacion(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region nombre domain property code
		
		/// <summary>
		/// nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid nombreDomainPropertyId = new global::System.Guid(0x07d1ff01, 0xd298, 0x4120, 0x8c, 0xee, 0x1a, 0x6e, 0x5f, 0xcd, 0xae, 0xdf);
		
		/// <summary>
		/// Storage for nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of nombre domain property.
		/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion.Nombre
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion/nombre.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion/nombre.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("07d1ff01-d298-4120-8cee-1a6e5fcdaedf")]
		public global::System.String nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				nombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Relacion.nombre domain property.
		/// </summary>
		internal sealed partial class nombrePropertyHandler : DslModeling::DomainPropertyValueHandler<Relacion, global::System.String>
		{
			private nombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Relacion.nombre domain property value handler.
			/// </summary>
			public static readonly nombrePropertyHandler Instance = new nombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Relacion.nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return nombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Relacion element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Relacion element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region cMax domain property code
		
		/// <summary>
		/// cMax domain property Id.
		/// </summary>
		public static readonly global::System.Guid cMaxDomainPropertyId = new global::System.Guid(0x491d2aa0, 0x0df9, 0x4217, 0xb2, 0x1a, 0xa6, 0xf7, 0x82, 0xf3, 0x67, 0x16);
		
		/// <summary>
		/// Storage for cMax
		/// </summary>
		private global::System.String cMaxPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of cMax domain property.
		/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion.CMax
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion/cMax.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion/cMax.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("491d2aa0-0df9-4217-b21a-a6f782f36716")]
		public global::System.String cMax
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return cMaxPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				cMaxPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Relacion.cMax domain property.
		/// </summary>
		internal sealed partial class cMaxPropertyHandler : DslModeling::DomainPropertyValueHandler<Relacion, global::System.String>
		{
			private cMaxPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Relacion.cMax domain property value handler.
			/// </summary>
			public static readonly cMaxPropertyHandler Instance = new cMaxPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Relacion.cMax domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return cMaxDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Relacion element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.cMaxPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Relacion element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.cMaxPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region cMin domain property code
		
		/// <summary>
		/// cMin domain property Id.
		/// </summary>
		public static readonly global::System.Guid cMinDomainPropertyId = new global::System.Guid(0xe6eb6f99, 0xe82a, 0x4541, 0xa9, 0x9d, 0x73, 0xeb, 0x5a, 0xd2, 0xef, 0x37);
		
		/// <summary>
		/// Storage for cMin
		/// </summary>
		private global::System.String cMinPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of cMin domain property.
		/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion.CMin
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion/cMin.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion/cMin.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("e6eb6f99-e82a-4541-a99d-73eb5ad2ef37")]
		public global::System.String cMin
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return cMinPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				cMinPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Relacion.cMin domain property.
		/// </summary>
		internal sealed partial class cMinPropertyHandler : DslModeling::DomainPropertyValueHandler<Relacion, global::System.String>
		{
			private cMinPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Relacion.cMin domain property value handler.
			/// </summary>
			public static readonly cMinPropertyHandler Instance = new cMinPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Relacion.cMin domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return cMinDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Relacion element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.cMinPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Relacion element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.cMinPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region DenWebBD opposite domain role accessor
		/// <summary>
		/// Gets or sets DenWebBD.
		/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.Relacion
		/// </summary>
		public virtual DenWebBD DenWebBD
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.RelacionDomainRoleId) as DenWebBD;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.DenWebBDTieneRelacion.RelacionDomainRoleId, value);
			}
		}
		#endregion
		#region AtributoRelacion opposite domain role accessor
		
		/// <summary>
		/// Gets a list of AtributoRelacion.
		/// Descripción de
		/// UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.Relacion
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<AtributoRelacion> AtributoRelacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<AtributoRelacion>, AtributoRelacion>(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.RelacionDomainRoleId);
			}
		}
		#endregion
		#region Entidad opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Entidad.
		/// Descripción de
		/// UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion.Relacion
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Entidad> Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Entidad>, Entidad>(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadReferenciasRelacion.RelacionDomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacion.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacion sourceAtributoRelacion1 = sourceElement as global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacion;
			if (sourceAtributoRelacion1 != null)
			{
				// Create link for path RelacionTieneAtributoRelacion.AtributoRelacion
				this.AtributoRelacion.Add(sourceAtributoRelacion1);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacion sourceAtributoRelacion1 = sourceElement as global::UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacion;
			if (sourceAtributoRelacion1 != null)
			{
				// Delete link for path RelacionTieneAtributoRelacion.AtributoRelacion
				
				foreach (DslModeling::ElementLink link in global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.GetLinks((global::UPM_IPS.CAFAMCMDGProyectoIPS2025.Relacion)this, sourceAtributoRelacion1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.RelacionDomainRoleId, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.AtributoRelacionDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// DomainClass Atributo
	/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.Atributo
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Atributo.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Atributo.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("ae9a19e8-c8af-47d8-87fe-126755a703de")]
	public abstract partial class Atributo : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Atributo domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xae9a19e8, 0xc8af, 0x47d8, 0x87, 0xfe, 0x12, 0x67, 0x55, 0xa7, 0x03, 0xde);
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		protected Atributo(DslModeling::Partition partition, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region nombre domain property code
		
		/// <summary>
		/// nombre domain property Id.
		/// </summary>
		public static readonly global::System.Guid nombreDomainPropertyId = new global::System.Guid(0xcc61d82a, 0xc4a8, 0x4d84, 0xba, 0x41, 0xf1, 0xf3, 0x6a, 0x80, 0x24, 0x79);
		
		/// <summary>
		/// Storage for nombre
		/// </summary>
		private global::System.String nombrePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of nombre domain property.
		/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.Atributo.Nombre
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Atributo/nombre.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Atributo/nombre.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("cc61d82a-c4a8-4d84-ba41-f1f36a802479")]
		public global::System.String nombre
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return nombrePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				nombrePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Atributo.nombre domain property.
		/// </summary>
		internal sealed partial class nombrePropertyHandler : DslModeling::DomainPropertyValueHandler<Atributo, global::System.String>
		{
			private nombrePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Atributo.nombre domain property value handler.
			/// </summary>
			public static readonly nombrePropertyHandler Instance = new nombrePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Atributo.nombre domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return nombreDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Atributo element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.nombrePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Atributo element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.nombrePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region tipo domain property code
		
		/// <summary>
		/// tipo domain property Id.
		/// </summary>
		public static readonly global::System.Guid tipoDomainPropertyId = new global::System.Guid(0x9fc43c03, 0x1da9, 0x4964, 0xa3, 0x8c, 0x7c, 0x05, 0x7d, 0x7e, 0x08, 0xcb);
		
		/// <summary>
		/// Storage for tipo
		/// </summary>
		private global::System.String tipoPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of tipo domain property.
		/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.Atributo.Tipo
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Atributo/tipo.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.Atributo/tipo.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("9fc43c03-1da9-4964-a38c-7c057d7e08cb")]
		public global::System.String tipo
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return tipoPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				tipoPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Atributo.tipo domain property.
		/// </summary>
		internal sealed partial class tipoPropertyHandler : DslModeling::DomainPropertyValueHandler<Atributo, global::System.String>
		{
			private tipoPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Atributo.tipo domain property value handler.
			/// </summary>
			public static readonly tipoPropertyHandler Instance = new tipoPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Atributo.tipo domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return tipoDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Atributo element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.tipoPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Atributo element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.tipoPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
	}
}
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// DomainClass AtributoEntidad
	/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoEntidad
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoEntidad.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoEntidad.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("aa43e288-a17b-49a8-bdbd-7dd844296a44")]
	public partial class AtributoEntidad : Atributo
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// AtributoEntidad domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xaa43e288, 0xa17b, 0x49a8, 0xbd, 0xbd, 0x7d, 0xd8, 0x44, 0x29, 0x6a, 0x44);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoEntidad(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoEntidad(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Entidad opposite domain role accessor
		/// <summary>
		/// Gets or sets Entidad.
		/// Descripción de
		/// UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.AtributoEntidad
		/// </summary>
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.AtributoEntidadDomainRoleId) as Entidad;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoEntidad.AtributoEntidadDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// DomainClass AtributoRelacion
	/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacion
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacion.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacion.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("fb2bb542-1a8d-4ba9-8162-1fd5792f67ae")]
	public partial class AtributoRelacion : Atributo
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// AtributoRelacion domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xfb2bb542, 0x1a8d, 0x4ba9, 0x81, 0x62, 0x1f, 0xd5, 0x79, 0x2f, 0x67, 0xae);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoRelacion(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoRelacion(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Relacion opposite domain role accessor
		/// <summary>
		/// Gets or sets Relacion.
		/// Descripción de
		/// UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.AtributoRelacion
		/// </summary>
		public virtual Relacion Relacion
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.AtributoRelacionDomainRoleId) as Relacion;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionTieneAtributoRelacion.AtributoRelacionDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// DomainClass AtributoClave
	/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoClave
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoClave.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoClave.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("243a0055-cb5e-49d4-8d0e-596aeab1c023")]
	public partial class AtributoClave : Atributo
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// AtributoClave domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x243a0055, 0xcb5e, 0x49d4, 0x8d, 0x0e, 0x59, 0x6a, 0xea, 0xb1, 0xc0, 0x23);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoClave(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AtributoClave(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region DomainProperty1 domain property code
		
		/// <summary>
		/// DomainProperty1 domain property Id.
		/// </summary>
		public static readonly global::System.Guid DomainProperty1DomainPropertyId = new global::System.Guid(0xed7177c1, 0xe0b3, 0x4902, 0xa6, 0x98, 0x2c, 0x4e, 0xe6, 0xfe, 0x16, 0x31);
		
		/// <summary>
		/// Storage for DomainProperty1
		/// </summary>
		private global::System.String domainProperty1PropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of DomainProperty1 domain property.
		/// Descripción de UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoClave.Domain Property1
		/// </summary>
		[DslDesign::DisplayNameResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoClave/DomainProperty1.DisplayName", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoClave/DomainProperty1.Description", typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DomainModel), "UPM_IPS.CAFAMCMDGProyectoIPS2025.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("ed7177c1-e0b3-4902-a698-2c4ee6fe1631")]
		public global::System.String DomainProperty1
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return domainProperty1PropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DomainProperty1PropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the AtributoClave.DomainProperty1 domain property.
		/// </summary>
		internal sealed partial class DomainProperty1PropertyHandler : DslModeling::DomainPropertyValueHandler<AtributoClave, global::System.String>
		{
			private DomainProperty1PropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the AtributoClave.DomainProperty1 domain property value handler.
			/// </summary>
			public static readonly DomainProperty1PropertyHandler Instance = new DomainProperty1PropertyHandler();
		
			/// <summary>
			/// Gets the Id of the AtributoClave.DomainProperty1 domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return DomainProperty1DomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(AtributoClave element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.domainProperty1PropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(AtributoClave element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.domainProperty1PropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Entidad opposite domain role accessor
		/// <summary>
		/// Gets or sets Entidad.
		/// Descripción de
		/// UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.AtributoClave
		/// </summary>
		public virtual Entidad Entidad
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.AtributoClaveDomainRoleId) as Entidad;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadTieneAtributoClave.AtributoClaveDomainRoleId, value);
			}
		}
		#endregion
	}
}
