//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "CAFAMCMDG_ProyectoIPS2025";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"CAFAMCMDGProyectoIPS2025";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID CAFAMCMDGProyectoIPS2025DiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CAFAMCMDGProyectoIPS2025CommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID CAFAMCMDGProyectoIPS2025ExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CAFAMCMDGProyectoIPS2025CommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewCAFAMCMDGProyectoIPS2025ExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(CAFAMCMDGProyectoIPS2025CommandSetId), 0x0001);
	
		// Package identifier
		public const string CAFAMCMDGProyectoIPS2025PackageId = "f482d598-6274-460b-a3c0-9424f70b68e1";
		
		// Editor factory identifier
		public const string CAFAMCMDGProyectoIPS2025EditorFactoryId = "fab3049f-7e36-4c94-80b4-4557f5e4a3b2";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string CAFAMCMDGProyectoIPS2025ModelExplorerToolWindowId = "b05fb146-85ae-440f-a4dc-fbcfa8896b86";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string CAFAMCMDGProyectoIPS2025CommandSetId = "9ff8a468-e7e3-451c-939d-60c3fae6b528";
	}
}