//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;

namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[global::System.Runtime.InteropServices.Guid(Constants.CAFAMCMDGProyectoIPS2025EditorFactoryId)]
	internal partial class CAFAMCMDGProyectoIPS2025EditorFactory : CAFAMCMDGProyectoIPS2025EditorFactoryBase
	{
		/// <summary>
		/// Constructs a new CAFAMCMDGProyectoIPS2025EditorFactory.
		/// </summary>
		public CAFAMCMDGProyectoIPS2025EditorFactory(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider)
		{
		}
	}

	/// <summary>
	/// Factory for creating our editors
	/// </summary>
	internal abstract class CAFAMCMDGProyectoIPS2025EditorFactoryBase : DslShell::ModelingEditorFactory
	{
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="serviceProvider">Service provider used to access VS services.</param>
		protected CAFAMCMDGProyectoIPS2025EditorFactoryBase(global::System.IServiceProvider serviceProvider) : base(serviceProvider)
		{
		}

		/// <summary>
		/// Called by the shell to ask the editor to create a new document object.
		/// </summary>
		public override DslShell::ModelingDocData CreateDocData(string fileName, VSShellInterop::IVsHierarchy hierarchy, uint itemId)
		{
			// Create the document type supported by this editor.
			return new CAFAMCMDGProyectoIPS2025DocData(this.ServiceProvider, typeof(CAFAMCMDGProyectoIPS2025EditorFactory).GUID);
		}

		/// <summary>
		/// Called by the shell to ask the editor to create a new view object.
		/// </summary>
		protected override DslShell::ModelingDocView CreateDocView(DslShell::ModelingDocData docData, string physicalView, out string editorCaption)
		{
			// Create the view type supported by this editor.
			editorCaption = string.Empty;
			return new CAFAMCMDGProyectoIPS2025DocView(docData, this.ServiceProvider);
		}
	}
}

