//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;

namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true, AllowsBackgroundLoading = true)]
	[VSShell::ProvideToolWindow(typeof(CAFAMCMDGProyectoIPS2025ExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(CAFAMCMDGProyectoIPS2025ExplorerToolWindow), Constants.CAFAMCMDGProyectoIPS2025EditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@CAFAMCMDGProyectoIPS2025ToolboxTab;UPM_IPS.CAFAMCMDGProyectoIPS2025.Dsl.dll", "UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025ToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025ToolboxTab",
					"@EntidadToolboxItem;UPM_IPS.CAFAMCMDGProyectoIPS2025.Dsl.dll", 
					"UPM_IPS.CAFAMCMDGProyectoIPS2025.EntidadToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Entidad", 
					"@EntidadToolboxBitmap;UPM_IPS.CAFAMCMDGProyectoIPS2025.Dsl.dll", 
					0xff00ff,
					Index = 0)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025ToolboxTab",
					"@RelacionToolboxItem;UPM_IPS.CAFAMCMDGProyectoIPS2025.Dsl.dll", 
					"UPM_IPS.CAFAMCMDGProyectoIPS2025.RelacionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"Relacion", 
					"@RelacionToolboxBitmap;UPM_IPS.CAFAMCMDGProyectoIPS2025.Dsl.dll", 
					0xff00ff,
					Index = 1)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025ToolboxTab",
					"@AtributoClaveToolboxItem;UPM_IPS.CAFAMCMDGProyectoIPS2025.Dsl.dll", 
					"UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoClaveToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AtributoClave", 
					"@AtributoClaveToolboxBitmap;UPM_IPS.CAFAMCMDGProyectoIPS2025.Dsl.dll", 
					0xff00ff,
					Index = 2)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025ToolboxTab",
					"@AtributoEntidadToolboxItem;UPM_IPS.CAFAMCMDGProyectoIPS2025.Dsl.dll", 
					"UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoEntidadToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AtributoEntidad", 
					"@AtributoEntidadToolboxBitmap;UPM_IPS.CAFAMCMDGProyectoIPS2025.Dsl.dll", 
					0xff00ff,
					Index = 3)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025ToolboxTab",
					"@AtributoRelacionToolboxItem;UPM_IPS.CAFAMCMDGProyectoIPS2025.Dsl.dll", 
					"UPM_IPS.CAFAMCMDGProyectoIPS2025.AtributoRelacionToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"AtributoRelacion", 
					"@AtributoRelacionToolboxBitmap;UPM_IPS.CAFAMCMDGProyectoIPS2025.Dsl.dll", 
					0xff00ff,
					Index = 4)]
	[VSShell::ProvideStaticToolboxItem("UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025ToolboxTab",
					"@ConectorERToolboxItem;UPM_IPS.CAFAMCMDGProyectoIPS2025.Dsl.dll", 
					"UPM_IPS.CAFAMCMDGProyectoIPS2025.ConectorERToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ConectorER", 
					"@ConectorERToolboxBitmap;UPM_IPS.CAFAMCMDGProyectoIPS2025.Dsl.dll", 
					0xff00ff,
					Index = 5)]
	[VSShell::ProvideEditorFactory(typeof(CAFAMCMDGProyectoIPS2025EditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(CAFAMCMDGProyectoIPS2025EditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[VSShell::ProvideEditorLogicalView(typeof(CAFAMCMDGProyectoIPS2025EditorFactory), "{7651A702-06E5-11D1-8EBD-00A0C90F26EA}")] // Designer logical view GUID i.e. VSConstants.LOGVIEWID_Designer
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"CAFAMCMDGProyectoIPS2025", typeof(CAFAMCMDGProyectoIPS2025EditorFactory))]

	internal abstract partial class CAFAMCMDGProyectoIPS2025PackageBase : DslShell::AsyncModelingPackage
	{
		protected global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025ToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected async override System.Threading.Tasks.Task InitializeAsync(CancellationToken cancellationToken, IProgress<VSShell.ServiceProgressData> progress)
		{
			await base.InitializeAsync(cancellationToken, progress);

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new CAFAMCMDGProyectoIPS2025EditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025ToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			CAFAMCMDGProyectoIPS2025CommandSet commandSet = new CAFAMCMDGProyectoIPS2025CommandSet(this);
			await commandSet.InitializeAsync(cancellationToken);
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			CAFAMCMDGProyectoIPS2025ClipboardCommandSet clipboardCommandSet = new CAFAMCMDGProyectoIPS2025ClipboardCommandSet(this);
			await clipboardCommandSet.InitializeAsync(cancellationToken);
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(CAFAMCMDGProyectoIPS2025ExplorerToolWindow));

			if (cancellationToken.IsCancellationRequested)
			{
				return;
			}

			await JoinableTaskFactory.SwitchToMainThreadAsync();

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			await this.SetupDynamicToolboxAsync(cancellationToken);
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch (global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}

		public override VSShellInterop::IVsAsyncToolWindowFactory GetAsyncToolWindowFactory(Guid toolWindowType)
		{
			if (toolWindowType == typeof(CAFAMCMDGProyectoIPS2025ExplorerToolWindow).GUID)
			{
				return this;
			}

			return base.GetAsyncToolWindowFactory(toolWindowType);
		}
	}
}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace UPM_IPS.CAFAMCMDGProyectoIPS2025
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[global::Microsoft.VisualStudio.TextTemplating.VSHost.ProvideDirectiveProcessor(typeof(global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DirectiveProcessor), global::UPM_IPS.CAFAMCMDGProyectoIPS2025.CAFAMCMDGProyectoIPS2025DirectiveProcessor.CAFAMCMDGProyectoIPS2025DirectiveProcessorName, "A directive processor that provides access to CAFAMCMDGProyectoIPS2025 files")]
	[global::System.Runtime.InteropServices.Guid(Constants.CAFAMCMDGProyectoIPS2025PackageId)]
	internal sealed partial class CAFAMCMDGProyectoIPS2025Package : CAFAMCMDGProyectoIPS2025PackageBase
	{
	}
}